microservice-chart:
  namespace: "checkout"
  nameOverride: ""
  fullnameOverride: "pagopa-checkout-identity-provider-mock"
  image:
    repository: pagopaucommonacr.azurecr.io/pagopacheckoutidentityprovidermock
    tag: "latest"
    pullPolicy: Always
  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /health/liveness
      port: 8090
    initialDelaySeconds: 10
    failureThreshold: 6
    periodSeconds: 90
    timeoutSeconds: 3
  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /health/readiness
      port: 8090
    initialDelaySeconds: 10
    failureThreshold: 6
    periodSeconds: 10
    timeoutSeconds: 3
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8090
  ingress:
    create: true
    host: "weuuat.checkout.internal.uat.platform.pagopa.it"
    path: /pagopa-checkout-identity-provider-mock/(.*)
    servicePort: 8090
  serviceAccount:
    name: "checkout-workload-identity"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - all
  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"
  envConfig:
    DEFAULT_LOGGING_LEVEL: "info"
  envSecret:
    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
  keyvault:
    name: "pagopa-u-checkout-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  secretProviderClass:
    secretProviderClass:
      create: false
  azure:
    workloadIdentityClientId: "61f9e998-9676-42fa-9435-554586259190"
